/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmOrdenFinal.java
 *
 * Created on 25/09/2011, 13:28:56
 */
package Ventanas_Transporte;

import Clases_Modulo_Transporte.OrdenServicio;
import Hibernate.GestorHibernate;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Charito
 */
public class frmOrdenFinal extends frmOrdenCarga {
GestorHibernate gestor = new GestorHibernate();
OrdenServicio orden = new OrdenServicio();
    /** Creates new form frmOrdenFinal */
    public frmOrdenFinal() {
        initComponents();
        List lista = gestor.listarClaseFitradaPorLong(OrdenServicio.class, "Numero Orden", orden.getNumeroOrden());
        labelNumeroOrden.setText((String) lista.get(lista.size()));
        List lista1 = gestor.listarClaseFitradaPorString(OrdenServicio.class, "Fecha Orden", orden.getFecha());
        labelFecha.setText((String) lista1.get(lista1.size()));
        List lista2= gestor.listarClaseFitradaPorString(OrdenServicio.class, "Hora Orden", orden.getHora());
        labelHora.setText((String) lista2.get(lista2.size()));
        List lista3= gestor.listarClaseFitradaPorString(OrdenServicio.class, "Tipo Servicio", orden.getTipoServicio().getNombreTipoServicio());
        LabelTipoServicio.setText((String) lista3.get(lista3.size()));
        List lista4= gestor.listarClaseFitradaPorString(OrdenServicio.class, "Estacion de Servicio", orden.getEstacionServicio().getRazonSocial());
        labelEstacion.setText((String) lista4.get(lista4.size()));
        List lista5= gestor.listarClaseFitradaPorString(OrdenServicio.class, "Transportista", orden.getVehiculo().getTransportista().getNombre());
        labelTransportista.setText((String) lista5.get(lista5.size()));
        List lista6= gestor.listarClaseFitradaPorString(OrdenServicio.class, "Modelo Vehiculo", orden.getVehiculo().getModelo().getNombreModelo());
        labelVehiculo.setText((String) lista6.get(lista6.size()));
        List lista7=gestor.listarClaseFitradaPorString(OrdenServicio.class, "Dominio Vehiculo", orden.getVehiculo().getDominio());
        labelDominio.setText((String) lista7.get(lista7.size()));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelNumeroOrden = new javax.swing.JLabel();
        labelTransportista = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelVehiculo = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelDominio = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        LabelTipoServicio = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        labelEstacion = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnVerOrden = new javax.swing.JButton();
        btnVerOrden1 = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        setTitle("Orden de Servicio");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Orden de Servicio", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Orden N°:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 110, 60, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas_Transporte/logomenzio.PNG"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(24, 20, 0, 70);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Fecha:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(240, 30, 40, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Hora:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(370, 30, 40, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Emitida por:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(240, 60, 90, 20);

        labelFecha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelFecha.setText("26-09-2011");
        jPanel1.add(labelFecha);
        labelFecha.setBounds(280, 30, 70, 20);

        labelHora.setFont(new java.awt.Font("org.n", 0, 12)); // NOI18N
        labelHora.setText("9:00");
        jPanel1.add(labelHora);
        labelHora.setBounds(410, 30, 30, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Carolina Ricci");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(310, 60, 80, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Transportista:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 140, 90, 20);

        labelNumeroOrden.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelNumeroOrden.setText("112");
        jPanel1.add(labelNumeroOrden);
        labelNumeroOrden.setBounds(90, 110, 40, 20);

        labelTransportista.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelTransportista.setText("Juan Jose Lopez");
        jPanel1.add(labelTransportista);
        labelTransportista.setBounds(120, 140, 100, 20);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Vehiculo:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(30, 170, 60, 15);

        labelVehiculo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelVehiculo.setText("Mercedes Benz L 1624");
        jPanel1.add(labelVehiculo);
        labelVehiculo.setBounds(90, 170, 140, 15);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Dominio: ");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(250, 170, 80, 15);

        labelDominio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelDominio.setText("AST 568");
        jPanel1.add(labelDominio);
        labelDominio.setBounds(310, 170, 60, 14);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("Orden para:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(190, 110, 70, 15);

        LabelTipoServicio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LabelTipoServicio.setText("Carga de Combustible");
        jPanel1.add(LabelTipoServicio);
        LabelTipoServicio.setBounds(270, 110, 140, 15);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("Estacion de Servicio: ");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(30, 200, 130, 15);

        labelEstacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelEstacion.setText("La Esquina");
        jPanel1.add(labelEstacion);
        labelEstacion.setBounds(160, 200, 70, 15);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logomenzio.PNG"))); // NOI18N
        jPanel1.add(jLabel20);
        jLabel20.setBounds(30, 20, 100, 80);

        btnVerOrden.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnVerOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imprimir.png"))); // NOI18N
        btnVerOrden.setText("Imprimir");

        btnVerOrden1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnVerOrden1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        btnVerOrden1.setText("Cancelar");
        btnVerOrden1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerOrden1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(btnVerOrden1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(btnVerOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(162, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVerOrden1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(btnVerOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(11, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerOrden1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerOrden1ActionPerformed
    int respuesta = JOptionPane.showConfirmDialog(null, "¿Confirma que desea cancelar la operación?");
    if (respuesta==0){
    dispose();
    }
    }//GEN-LAST:event_btnVerOrden1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTipoServicio;
    private javax.swing.JButton btnVerOrden;
    private javax.swing.JButton btnVerOrden1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelDominio;
    private javax.swing.JLabel labelEstacion;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelNumeroOrden;
    private javax.swing.JLabel labelTransportista;
    private javax.swing.JLabel labelVehiculo;
    // End of variables declaration//GEN-END:variables
}
