/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmOrdenTaller.java
 *
 * Created on 25/09/2011, 13:20:44
 */
package Ventanas_Transporte;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Charito
 */
public class frmOrdenTaller extends javax.swing.JInternalFrame {

    /** Creates new form frmOrdenTaller */
    public frmOrdenTaller() {
        initComponents();
    
        txtFecha.setEnabled(false);
        txtHora.setEnabled(false);
        txtFecha.setEditable(false);
        txtHora.setEditable(false);
        
        //borrar el icono del InternalFrame
       this.setFrameIcon(new ImageIcon("Imagenes/Aceptar.png")); 
        
     //Las siguientes lineas son para dar a la pantalla el tamaño requerido y luego centrarla en la pantalla.
        Toolkit kit = Toolkit.getDefaultToolkit();
        Dimension tamanioPantalla = kit.getScreenSize();
        int ancho = 750;
        int alto = 625;
        int posX = (int) ((tamanioPantalla.width - ancho) / 2);
//        int posY = (int) ((tamanioPantalla.height - alto) / 2);
        this.setSize(ancho, alto);
        this.setLocation(posX, 0);
  }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtFecha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransportista = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDominio = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        cmbVehiculo = new javax.swing.JComboBox();
        btnAgregarTransportista = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtAnioCompra = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmbTalleres = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtEspecialidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLocalidad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDepartamento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtProvincia = new javax.swing.JTextField();
        txtDomicilio = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaDesperfecto = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        btnEmitirOrden = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Reparacion");

        jPanel1.setLayout(null);

        txtFecha.setText("03-10-2011");
        jPanel1.add(txtFecha);
        txtFecha.setBounds(60, 10, 70, 20);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Fecha");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 40, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Hora");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 10, 40, 20);

        txtHora.setText("16:00");
        jPanel1.add(txtHora);
        txtHora.setBounds(180, 10, 50, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Usuario");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(560, 0, 60, 40);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Transportista", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPanel2.setLayout(null);

        tblTransportista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Jose Torrea", "28.979.456"}
            },
            new String [] {
                "Transportista", "Numero Documento"
            }
        ));
        jScrollPane1.setViewportView(tblTransportista);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(120, 30, 452, 100);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Vehiculo");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(70, 180, 90, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Dominio");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(410, 180, 60, 20);
        jPanel2.add(txtDominio);
        txtDominio.setBounds(470, 180, 100, 20);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Año de Compra");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(40, 210, 100, 20);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Estado");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(420, 210, 50, 20);
        jPanel2.add(txtEstado);
        txtEstado.setBounds(470, 210, 170, 20);

        jPanel2.add(cmbVehiculo);
        cmbVehiculo.setBounds(130, 180, 200, 20);

        btnAgregarTransportista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Aceptar.png"))); // NOI18N
        jPanel2.add(btnAgregarTransportista);
        btnAgregarTransportista.setBounds(580, 70, 40, 30);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Jose Torrea");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(360, 140, 110, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Transportista:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(260, 140, 110, 17);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(40, 170, 600, 10);
        jPanel2.add(txtAnioCompra);
        txtAnioCompra.setBounds(130, 210, 100, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 40, 690, 250);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Proveedor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPanel3.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Taller de Reparación");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 30, 120, 20);

        cmbTalleres.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "El Guri" }));
        jPanel3.add(cmbTalleres);
        cmbTalleres.setBounds(130, 30, 210, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Especialidad");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(390, 30, 80, 20);
        jPanel3.add(txtEspecialidad);
        txtEspecialidad.setBounds(470, 30, 190, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Domicilio");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(70, 60, 70, 20);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Localidad");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(410, 60, 70, 20);
        jPanel3.add(txtLocalidad);
        txtLocalidad.setBounds(470, 60, 190, 20);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Departamento");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(40, 90, 100, 20);
        jPanel3.add(txtDepartamento);
        txtDepartamento.setBounds(130, 90, 200, 20);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Provincia");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(410, 90, 80, 20);
        jPanel3.add(txtProvincia);
        txtProvincia.setBounds(470, 90, 190, 20);

        txtDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDomicilioActionPerformed(evt);
            }
        });
        jPanel3.add(txtDomicilio);
        txtDomicilio.setBounds(130, 60, 230, 20);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(30, 130, 630, 10);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Desperfecto");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(40, 180, 90, 15);

        areaDesperfecto.setColumns(20);
        areaDesperfecto.setRows(5);
        jScrollPane2.setViewportView(areaDesperfecto);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(110, 140, 530, 100);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 290, 690, 250);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UsuarioLogueado.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(610, 10, 30, 30);

        btnEmitirOrden.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnEmitirOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Aceptar.png"))); // NOI18N
        btnEmitirOrden.setText("Emitir Orden");

        btnCancelar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(btnEmitirOrden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmitirOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDomicilioActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    int respuesta = JOptionPane.showConfirmDialog(null, "¿Confirma que desea cancelar la operación?");
    if (respuesta==0){
    dispose();
    }
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDesperfecto;
    private javax.swing.JButton btnAgregarTransportista;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEmitirOrden;
    private javax.swing.JComboBox cmbTalleres;
    private javax.swing.JComboBox cmbVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblTransportista;
    private javax.swing.JTextField txtAnioCompra;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtDominio;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtLocalidad;
    private javax.swing.JTextField txtProvincia;
    // End of variables declaration//GEN-END:variables
}
